In [1]:
import numpy as np
import pandas as pd

In [2]:
datadispo = pd.read_csv("../Data/raw_data/dispo_alimentaire.csv")

In [3]:
datadispo

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,NaN,NaN,45.0,4.70,4.28,1.41,3.0,NaN,0.0,3.0,NaN,2.0,NaN,NaN,NaN
15601,Îles Salomon,Viande de Volailles,animale,NaN,NaN,11.0,3.34,0.69,1.14,2.0,NaN,2.0,2.0,NaN,0.0,NaN,NaN,NaN
15602,Îles Salomon,"Viande, Autre",animale,NaN,NaN,0.0,0.06,NaN,0.04,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
15603,Îles Salomon,Vin,vegetale,NaN,NaN,0.0,0.07,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
15604,Îles Salomon,"Épices, Autres",vegetale,NaN,NaN,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [4]:
datadispo = datadispo.rename(columns={'Zone':'Pays'})

In [5]:
datadispo = datadispo[['Pays','Produit','Origine','Disponibilité alimentaire (Kcal/personne/jour)','Disponibilité alimentaire en quantité (kg/personne/an)','Disponibilité de matière grasse en quantité (g/personne/jour)','Disponibilité de protéines en quantité (g/personne/jour)','Disponibilité intérieure','Exportations - Quantité','Importations - Quantité','Nourriture','Aliments pour animaux','Autres Utilisations','Pertes','Production','Semences','Traitement','Variation de stock']]

In [6]:
datadispo

,Pays,Produit,Origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Aliments pour animaux,Autres Utilisations,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,NaN,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,45.0,4.70,4.28,1.41,3.0,NaN,0.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
15601,Îles Salomon,Viande de Volailles,animale,11.0,3.34,0.69,1.14,2.0,NaN,2.0,2.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
15602,Îles Salomon,"Viande, Autre",animale,0.0,0.06,NaN,0.04,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15603,Îles Salomon,Vin,vegetale,0.0,0.07,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15604,Îles Salomon,"Épices, Autres",vegetale,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [7]:
datadispo = datadispo.rename(columns={'Disponibilité intérieure':'Disponibilité intérieure (en tonne)', 'Exportations - Quantité':'Exportations - Quantité (en tonne)','Importations - Quantité':'Importations - Quantité (en tonne)','Nourriture':'Nourriture (en tonne)','Aliments pour animaux':'Aliments pour animaux (en tonne)','Autres Utilisations':'Autres Utilisations (en tonne)','Autres Utilisations':'Autres Utilisations (en tonne)','Pertes':'Pertes (en tonne)','Production':'Production (en tonne)','Semences':'Semences (en tonne)','Traitement':'Traitement (en tonne)'})

In [8]:
datadispo.dropna(how = 'all')

,Pays,Produit,Origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure (en tonne),Exportations - Quantité (en tonne),Importations - Quantité (en tonne),Nourriture (en tonne),Aliments pour animaux (en tonne),Autres Utilisations (en tonne),Pertes (en tonne),Production (en tonne),Semences (en tonne),Traitement (en tonne),Variation de stock
0,Afghanistan,Abats Comestible,animale,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,NaN,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,45.0,4.70,4.28,1.41,3.0,NaN,0.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
15601,Îles Salomon,Viande de Volailles,animale,11.0,3.34,0.69,1.14,2.0,NaN,2.0,2.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
15602,Îles Salomon,"Viande, Autre",animale,0.0,0.06,NaN,0.04,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15603,Îles Salomon,Vin,vegetale,0.0,0.07,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15604,Îles Salomon,"Épices, Autres",vegetale,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [9]:
datadispo = datadispo.fillna(0)
datadispo.sort_values(by=['Aliments pour animaux (en tonne)'], ascending=False).head(10)

,Pays,Produit,Origine,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure (en tonne),Exportations - Quantité (en tonne),Importations - Quantité (en tonne),Nourriture (en tonne),Aliments pour animaux (en tonne),Autres Utilisations (en tonne),Pertes (en tonne),Production (en tonne),Semences (en tonne),Traitement (en tonne),Variation de stock
3324,"Chine, continentale",Maïs,vegetale,54.0,6.78,0.18,1.17,212998.0,251.0,3269.0,9391.0,150000.0,35172.0,10250.0,218489.0,1650.0,6535.0,-8509.0
15391,États-Unis d'Amérique,Maïs,vegetale,92.0,12.24,0.26,1.67,292776.0,24655.0,3595.0,3917.0,128024.0,137023.0,0.0,353699.0,582.0,23230.0,-39863.0
2130,Brésil,Maïs,vegetale,240.0,28.01,0.98,5.31,54737.0,26780.0,979.0,5612.0,40487.0,0.0,8145.0,80538.0,386.0,108.0,0.0
3321,"Chine, continentale","Légumes, Autres",vegetale,203.0,308.07,1.76,11.47,500070.0,8084.0,304.0,426850.0,35582.0,0.0,37638.0,507850.0,0.0,0.0,0.0
3337,"Chine, continentale",Patates douces,vegetale,66.0,24.27,0.20,0.66,70420.0,120.0,14.0,33623.0,33270.0,0.0,3526.0,70526.0,0.0,0.0,0.0
3284,"Chine, continentale",Blé,vegetale,549.0,63.36,2.92,17.53,125247.0,563.0,5666.0,87783.0,26628.0,2929.0,2990.0,121926.0,4600.0,316.0,-1783.0
9830,Nigéria,Manioc,vegetale,262.0,118.86,0.58,1.22,53004.0,11.0,15.0,20636.0,26288.0,0.0,6080.0,53000.0,0.0,0.0,0.0
3323,"Chine, continentale",Manioc,vegetale,6.0,1.91,0.01,0.05,33590.0,41.0,29046.0,2645.0,22868.0,7940.0,138.0,4585.0,0.0,0.0,0.0
6235,Inde,Lait - Excl Beurre,animale,129.0,84.50,5.65,8.17,133443.0,2175.0,18.0,105807.0,22757.0,0.0,4878.0,135600.0,0.0,0.0,0.0
3348,"Chine, continentale",Pommes de Terre,vegetale,80.0,41.42,0.11,1.93,96068.0,377.0,503.0,57384.0,22165.0,221.0,4797.0,95942.0,3100.0,8400.0,0.0

In [10]:
datadispo.to_csv('../Data/processed_data/dispo_alimentaire_V2.csv', index=False)